name: workflow variables
on:
 push:
env:
 PYTHON_VERSION: 3.9
jobs:
  job1: 
   runs-on: ubuntu-latest
   steps:
    - name: Checkout code 
      uses: actions/checkout@v4 
    - name: Setup python ${{ PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
       python-version: ${{ PYTHON_VERSION }}
  job2:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout code 
      uses: actions/checkout@v4 
    - name: Setup python ${{ PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
       python-version: ${{ PYTHON_VERSION }}
